services:
  ai-racers:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-racers:latest
    container_name: ai-racers
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    labels:
      - "com.ai-racers.description=AI Racers - Model Comparison Tool"
      - "com.ai-racers.version=0.0.1"
    networks:
      - ai-racers-network

networks:
  ai-racers-network:
    driver: bridge
